/// The D29 validation checklist names error/correlation fixtures and requires
/// one fixture per signal/metric point form.
pub const D29_FIXTURES: &[&str] = &[
    "logs",
    "traces",
    "profiles",
    "metric_gauge",
    "metric_sum",
    "metric_histogram",
    "metric_exponential_histogram",
    "metric_summary",
    "uint_over_i64_max",
    "correlation_conflict",
    "timing_conflict",
    "unsupported_version",
    "strindex_outside_profiles",
    "non_finite_doubles",
    "plain_attribute_map",
    "paired_log_span_generated_ids",
    "histogram_bucket_count_mismatch",
    "summary_quantile_out_of_range",
    "monotonic_sum_negative",
    "delta_empty_interval",
    "exponential_scale_out_of_range",
    "profile_index_out_of_range",
];
