[package]
name = "otlp-native-example"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish = false

[dependencies]
sc-observability.workspace = true
sc-observability-log.workspace = true
sc-observability-otlp = { workspace = true, features = ["log-sink", "synchronous-client", "tokio-exporter"] }
sc-observability-types.workspace = true
log.workspace = true
tokio.workspace = true

[lints]
workspace = true
