//! Re-exports of the types-owned telemetry diagnostic codes.
#[doc(inline)]
pub use crate::error_codes::{
    SC_OBSERVABILITY_ADMIT_CLOSED, SC_OBSERVABILITY_ADMIT_DISK_BOUND,
    SC_OBSERVABILITY_ADMIT_PERSISTENCE, SC_OBSERVABILITY_ADMIT_SCHEMA_TOO_NEW,
    SC_OBSERVABILITY_ADMIT_STORE_UNAVAILABLE, SC_OBSERVABILITY_DELIVERY_DEADLINE,
    SC_OBSERVABILITY_DELIVERY_FAILED, SC_OBSERVABILITY_SUBMIT_CORRELATION_CONFLICT,
    SC_OBSERVABILITY_SUBMIT_DICTIONARY_REFERENCE, SC_OBSERVABILITY_SUBMIT_EMPTY,
    SC_OBSERVABILITY_SUBMIT_INVALID_JSON, SC_OBSERVABILITY_SUBMIT_TIMING_CONFLICT,
    SC_OBSERVABILITY_SUBMIT_UNSUPPORTED_VERSION, SC_OBSERVABILITY_SUBMIT_VALIDATION,
    SC_OBSERVABILITY_SUBMIT_VALUE_OUT_OF_RANGE, SC_OBSERVABILITY_TELEMETRY_CONFIG_FILE,
    SC_OBSERVABILITY_TELEMETRY_CONFIG_INVALID, SC_OBSERVABILITY_TELEMETRY_CONFIG_MISSING,
    SC_OBSERVABILITY_TELEMETRY_UNSUPPORTED, SC_OBSERVABILITY_TEST_DOUBLE_SCRIPTED_FAILURE,
};
