[package]
name = "sc-otel-cli"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Telemetry submission command-line client"

[[bin]]
name = "sc-otel"
path = "src/main.rs"

[dependencies]
sc-observability-otlp = { workspace = true, features = ["synchronous-client"] }
clap.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
