ARG BASE_IMAGE=quay.io/pypa/manylinux_2_28_x86_64
FROM ${BASE_IMAGE}
RUN dnf install -y bubblewrap git && dnf clean all
ENV PATH=/opt/python/cp310-cp310/bin:/root/.cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.94.1
COPY scripts/ci/python-packaging-requirements.txt /tmp/qualification-requirements.txt
RUN python -m pip install --disable-pip-version-check -r /tmp/qualification-requirements.txt
