[package]
name = "sc-observability-composition"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
sc-observability = { workspace = true, features = ["v1"] }
sc-observability-log = { workspace = true, features = ["v1"] }
sc-observe.workspace = true
sc-observability-otlp = { workspace = true, features = ["v1", "otlp-sdk", "sync-http"] }
sc-observability-types = { workspace = true, features = ["v1"] }
tokio.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tonic.workspace = true
opentelemetry-proto.workspace = true

[lints]
workspace = true
