pub const DEFAULT_OTLP_TIMEOUT_MS: u64 = 3_000;
pub const DEFAULT_OTLP_MAX_RETRIES: u32 = 3;
pub const DEFAULT_OTLP_INITIAL_BACKOFF_MS: u64 = 250;
pub const DEFAULT_OTLP_MAX_BACKOFF_MS: u64 = 5_000;
pub const DEFAULT_LOG_BATCH_SIZE: usize = 256;
pub const DEFAULT_TRACE_BATCH_SIZE: usize = 256;
pub const DEFAULT_METRIC_BATCH_SIZE: usize = 256;
pub const DEFAULT_METRIC_EXPORT_INTERVAL_MS: u64 = 5_000;
