//! Generate release documentation from the actual Clap tree, never a parallel flag list.
//! Only compiled into the test harness; it adds no production command or dependency.

use crate::cli::Cli;
use clap::{Command, CommandFactory};
use std::{fmt::Write, path::Path};

const REGENERATE: &str = "just cli-docs";

fn command_help(command: &mut Command, pages: &mut Vec<(String, String)>) {
    if command.is_hide_set() {
        return;
    }
    let name = command
        .get_bin_name()
        .unwrap_or(command.get_name())
        .to_owned();
    pages.push((name, command.render_long_help().to_string()));
    for child in command.get_subcommands_mut() {
        command_help(child, pages);
    }
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn reference() -> (String, String) {
    let version = env!("CARGO_PKG_VERSION");
    let mut command = Cli::command().term_width(100);
    command.build();
    let mut pages = Vec::new();
    command_help(&mut command, &mut pages);
    let mut markdown = format!(
        "# sc-otel CLI reference — {version}\n\n\
         Generated from the live Clap command tree. Do not edit this file.\n\
         Regenerate with `{REGENERATE}`. Source: `crates/sc-otel-cli/src/cli.rs` and its help text.\n\n"
    );
    let mut html = format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\
         <meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>sc-otel CLI reference {version} · Synaptic Canvas</title>\n\
         <style>body{{font-family:-apple-system,system-ui,sans-serif;max-width:64rem;margin:2rem auto;padding:0 1.5rem;line-height:1.6;color:#1a1a2e}}\n\
         nav a{{margin-right:1rem}}pre{{background:#f0f0f4;padding:1rem;overflow-x:auto;white-space:pre-wrap;overflow-wrap:anywhere}}\n\
         a{{color:#244b9b}}h2{{scroll-margin-top:1rem}}</style>\n</head>\n<body>\n\
         <nav aria-label=\"Site\"><a href=\"../../\">sc-observability</a>\
         <a href=\"cli-reference.md\" download>Download Markdown manual</a></nav>\n\
         <main><h1>sc-otel CLI reference — {version}</h1>\n\
         <p>Generated from the live Clap command tree. Source: cli.rs and its help text. \
         Updated automatically for every release. Do not edit generated output.</p>\n\
         <nav aria-label=\"Commands\"><ul>\n"
    );
    for (name, _) in &pages {
        let anchor = name.replace(' ', "-");
        writeln!(markdown, "- [{name}](#{anchor})").unwrap();
        writeln!(
            html,
            "<li><a href=\"{}\">{}</a></li>",
            escape(&format!("#{anchor}")),
            escape(name)
        )
        .unwrap();
    }
    markdown.push('\n');
    html.push_str("</ul></nav>\n");
    for (name, help) in pages {
        writeln!(
            markdown,
            "## {name}\n\n```text\n{}```\n",
            help.trim_end().to_owned() + "\n"
        )
        .unwrap();
        writeln!(
            html,
            "<section id=\"{}\"><h2>{}</h2><pre>{}</pre></section>",
            escape(&name.replace(' ', "-")),
            escape(&name),
            escape(help.trim_end())
        )
        .unwrap();
    }
    html.push_str("</main>\n</body>\n</html>\n");
    (markdown, html)
}

fn artifact(root: &Path, relative: &str, expected: &str, update: bool) {
    let path = root.join(relative);
    if update {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, expected).unwrap();
    } else {
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}; run {REGENERATE}", path.display()));
        assert_eq!(actual, expected, "{relative} is stale; run {REGENERATE}");
    }
}

#[test]
fn generated_manual_is_current() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    let update = std::env::var("SC_OTEL_UPDATE_DOCS").as_deref() == Ok("1");
    let (markdown, html) = reference();
    artifact(
        root,
        "docs/manual/sc-otel/cli-reference.md",
        &markdown,
        update,
    );
    artifact(
        root,
        "site/manual/sc-otel/cli-reference.md",
        &markdown,
        update,
    );
    artifact(root, "site/manual/sc-otel/index.html", &html, update);
}

#[test]
fn public_options_have_explanations() {
    fn check(command: &Command) {
        for arg in command.get_arguments().filter(|arg| !arg.is_hide_set()) {
            assert!(
                arg.get_help().is_some(),
                "{}: {} needs help",
                command.get_name(),
                arg.get_id()
            );
        }
        for child in command
            .get_subcommands()
            .filter(|child| !child.is_hide_set())
        {
            assert!(
                child.get_about().is_some(),
                "{} needs a description",
                child.get_name()
            );
            check(child);
        }
    }
    let mut command = Cli::command();
    command.build();
    check(&command);
}

#[test]
fn website_escapes_help_and_matches_markdown_commands() {
    assert_eq!(escape("<&\"'>"), "&lt;&amp;&quot;&#39;&gt;");
    let (markdown, html) = reference();
    for command in ["sc-otel", "sc-otel log", "sc-otel span", "sc-otel metric"] {
        assert!(markdown.contains(&format!("## {command}\n")));
        assert!(html.contains(&format!("<h2>{command}</h2>")));
    }
    assert!(!html.contains("<URL>"));
    assert!(html.contains("&lt;URL&gt;"));
}

#[test]
fn help_names_no_retired_store_command() {
    let (markdown, html) = reference();
    for retired in [
        "sc-otel emit",
        "sc-otel validate",
        "sc-otel flush",
        "sc-otel status",
        "--store",
        "--config",
        "--record-key",
        "--no-flush",
        "SQLite",
        "durable",
    ] {
        assert!(
            !markdown.contains(retired),
            "{retired} remains in the manual"
        );
        assert!(!html.contains(retired), "{retired} remains on the website");
    }
}
