//! Generate release documentation from the actual Clap tree, never a parallel flag list.
//! Only compiled into the test harness; it adds no production command or dependency.

use crate::{
    cli::Cli,
    error_codes::{EXIT_EXPORT, EXIT_INTERNAL, EXIT_OK, EXIT_USAGE, EXIT_VALIDATION},
};
use clap::{Command, CommandFactory};
use serde_json::{Value, json};
use std::{fmt::Write, path::Path};

const REGENERATE: &str = "just cli-docs";

fn command_help(command: &mut Command, pages: &mut Vec<(String, String)>) {
    if command.is_hide_set() {
        return;
    }
    let name = command
        .get_bin_name()
        .unwrap_or(command.get_name())
        .to_owned();
    pages.push((name, command.render_long_help().to_string()));
    for child in command.get_subcommands_mut() {
        command_help(child, pages);
    }
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn reference() -> (String, String) {
    let version = env!("CARGO_PKG_VERSION");
    let mut command = Cli::command().term_width(100);
    command.build();
    let mut pages = Vec::new();
    command_help(&mut command, &mut pages);
    let mut markdown = format!(
        "# sc-otel CLI reference — {version}\n\n\
         Generated from the live Clap command tree. Do not edit this file.\n\
         Regenerate with `{REGENERATE}`. Source: `crates/sc-otel-cli/src/cli.rs` and its help text.\n\n"
    );
    let mut html = format!(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\
         <meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>sc-otel CLI reference {version} · Synaptic Canvas</title>\n\
         <style>body{{font-family:-apple-system,system-ui,sans-serif;max-width:64rem;margin:2rem auto;padding:0 1.5rem;line-height:1.6;color:#1a1a2e}}\n\
         nav a{{margin-right:1rem}}pre{{background:#f0f0f4;padding:1rem;overflow-x:auto;white-space:pre-wrap;overflow-wrap:anywhere}}\n\
         a{{color:#244b9b}}h2{{scroll-margin-top:1rem}}</style>\n</head>\n<body>\n\
         <nav aria-label=\"Site\"><a href=\"../../\">sc-observability</a>\
         <a href=\"cli-reference.md\" download>Download Markdown manual</a></nav>\n\
         <main><h1>sc-otel CLI reference — {version}</h1>\n\
         <p>Generated from the live Clap command tree. Source: cli.rs and its help text. \
         Updated automatically for every release. Do not edit generated output.</p>\n\
         <nav aria-label=\"Commands\"><ul>\n"
    );
    for (name, _) in &pages {
        let anchor = name.replace(' ', "-");
        writeln!(markdown, "- [{name}](#{anchor})").expect("writing to String cannot fail");
        writeln!(
            html,
            "<li><a href=\"{}\">{}</a></li>",
            escape(&format!("#{anchor}")),
            escape(name)
        )
        .expect("writing to String cannot fail");
    }
    markdown.push('\n');
    html.push_str("</ul></nav>\n");
    for (name, help) in pages {
        writeln!(
            markdown,
            "## {name}\n\n```text\n{}```\n",
            help.trim_end().to_owned() + "\n"
        )
        .expect("writing to String cannot fail");
        writeln!(
            html,
            "<section id=\"{}\"><h2>{}</h2><pre>{}</pre></section>",
            escape(&name.replace(' ', "-")),
            escape(&name),
            escape(help.trim_end())
        )
        .expect("writing to String cannot fail");
    }
    html.push_str("</main>\n</body>\n</html>\n");
    (markdown, html)
}

fn artifact(root: &Path, relative: &str, expected: &str, update: bool) {
    let path = root.join(relative);
    if update {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, expected).unwrap();
    } else {
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}; run {REGENERATE}", path.display()));
        assert!(
            artifact_text_matches(&actual, expected),
            "{relative} is stale; run {REGENERATE}"
        );
    }
}

fn artifact_text_matches(actual: &str, expected: &str) -> bool {
    actual.replace("\r\n", "\n") == expected
}

#[test]
fn generated_artifacts_accept_crlf_checkout_without_hiding_content_drift() {
    let expected = "first line\nsecond line\n";
    let crlf_checkout = expected.replace('\n', "\r\n");
    assert!(artifact_text_matches(&crlf_checkout, expected));

    let changed_content = crlf_checkout.replace("second line", "changed line");
    assert!(!artifact_text_matches(&changed_content, expected));
}

#[test]
fn generated_artifacts_are_current() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    let update = std::env::var("SC_OTEL_UPDATE_DOCS").as_deref() == Ok("1");
    let (markdown, html) = reference();
    artifact(
        root,
        "docs/manual/sc-otel/cli-reference.md",
        &markdown,
        update,
    );
    artifact(
        root,
        "site/manual/sc-otel/cli-reference.md",
        &markdown,
        update,
    );
    artifact(root, "site/manual/sc-otel/index.html", &html, update);
    artifact(
        root,
        "schema/cli/sc-otel/commands/1.6.0.json",
        &json_artifact(&command_contract()),
        update,
    );
    artifact(
        root,
        "schema/cli/sc-otel/results/v2.json",
        &json_artifact(&result_contract()),
        update,
    );
}

/// Projects the built Clap tree rather than treating help text as a second
/// parser specification. This is test-only: it does not add a CLI dependency
/// or alter the runtime command surface.
fn command_contract() -> Value {
    command_contract_for(&Cli::command())
}

fn command_contract_for(command: &Command) -> Value {
    let mut arguments = command
        .get_arguments()
        .map(|argument| {
            let action = argument.get_action();
            let num_args = effective_num_args(argument);
            let mut conflicts = command
                .get_arg_conflicts_with(argument)
                .into_iter()
                .map(|conflict| conflict.get_id().as_str().to_owned())
                .collect::<Vec<_>>();
            conflicts.sort();
            let mut flags = argument
                .get_long_and_visible_aliases()
                .unwrap_or_default()
                .into_iter()
                .map(|name| format!("--{name}"))
                .chain(
                    argument
                        .get_short_and_visible_aliases()
                        .unwrap_or_default()
                        .into_iter()
                        .map(|name| format!("-{name}")),
                )
                .collect::<Vec<_>>();
            flags.sort();
            let mut allowed_values = argument
                .get_possible_values()
                .into_iter()
                .flat_map(|value| {
                    value
                        .get_name_and_aliases()
                        .map(str::to_owned)
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>();
            allowed_values.sort();
            allowed_values.dedup();
            let value_names = argument.get_value_names().map(|names| {
                names
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
            });
            let mut contract = json!({
                "id": argument.get_id().as_str(),
                "flags": flags,
                "action": format!("{action:?}"),
                "num_args": {
                    "min": num_args.min_values(),
                    "max": num_args.max_values(),
                },
                "global": argument.is_global_set(),
                "value_name": value_names,
                "required": argument.is_required_set(),
                "default_values": argument.get_default_values().iter().map(|value| value.to_string_lossy()).collect::<Vec<_>>(),
                "allowed_values": allowed_values,
                "conflicts_with": conflicts,
            });
            if let Some(constraint) = parser_constraint(command, argument) {
                contract["value_constraint"] = json!(constraint);
            }
            contract
        })
        .collect::<Vec<_>>();
    arguments.sort_by(|left, right| left["id"].as_str().cmp(&right["id"].as_str()));

    let mut groups = command
        .get_groups()
        .map(|group| {
            let mut group = group.clone();
            let mut members = group
                .get_args()
                .map(|member| member.as_str().to_owned())
                .collect::<Vec<_>>();
            members.sort();
            json!({
                "id": group.get_id().as_str(),
                "required": group.is_required_set(),
                "multiple": group.is_multiple(),
                "members": members,
            })
        })
        .collect::<Vec<_>>();
    groups.sort_by(|left, right| left["id"].as_str().cmp(&right["id"].as_str()));

    let mut subcommands = command
        .get_subcommands()
        .map(command_contract_for)
        .collect::<Vec<_>>();
    subcommands.sort_by(|left, right| left["name"].as_str().cmp(&right["name"].as_str()));

    json!({
        "name": command.get_name(),
        "aliases": command.get_all_aliases().collect::<Vec<_>>(),
        "arguments": arguments,
        "groups": groups,
        "subcommands": subcommands,
    })
}

fn effective_num_args(argument: &clap::Arg) -> clap::builder::ValueRange {
    argument.get_num_args().unwrap_or_else(|| {
        if argument.get_action().takes_values() {
            clap::builder::ValueRange::SINGLE
        } else {
            clap::builder::ValueRange::EMPTY
        }
    })
}

/// The result is not a JSON response model: successful sends deliberately
/// print nothing. It records the actual process streams and exit behavior in
/// `main.rs`, including Clap's multi-line diagnostics and the panic path.
fn result_contract() -> Value {
    json!({
        "contract": "sc-otel.result/v2",
        "commands": ["log", "span", "metric"],
        "outcomes": [
            {
                "case": "clap_display",
                "examples": ["--help", "--version"],
                "exit_code": EXIT_OK,
                "stdout": {"kind": "clap_rendered"},
                "stderr": {"kind": "empty"},
            },
            {
                "case": "clap_usage_error",
                "exit_code": EXIT_USAGE,
                "stdout": {"kind": "empty"},
                "stderr": {"kind": "clap_rendered_multiline"},
            },
            {
                "case": "export_success",
                "exit_code": EXIT_OK,
                "stdout": {"kind": "empty"},
                "stderr": {"kind": "empty"},
            },
            {
                "case": "validation_error",
                "exit_code": EXIT_VALIDATION,
                "stdout": {"kind": "empty"},
                "stderr": {"kind": "sc_otel_prefixed_error", "format": "sc-otel: {error}\\n"},
            },
            {
                "case": "export_error",
                "exit_code": EXIT_EXPORT,
                "stdout": {"kind": "empty"},
                "stderr": {"kind": "sc_otel_prefixed_error", "format": "sc-otel: {error_code}: {error}; check the endpoint and --root-certificate; raise --timeout if needed\\n"},
            },
            {
                "case": "caught_panic",
                "exit_code": EXIT_INTERNAL,
                "stdout": {"kind": "empty"},
                "stderr": {"kind": "internal_diagnostic_multiline", "format": "sc-otel: unexpected internal error [{code}].\\nRecovery: ..."},
            },
        ],
    })
}

fn parser_constraint(command: &Command, argument: &clap::Arg) -> Option<String> {
    const INVALID_VALUE: &str = "__sc_otel_contract_invalid_value__";

    if !argument.get_action().takes_values() || !argument.get_possible_values().is_empty() {
        return None;
    }

    let flag = argument
        .get_long()
        .map(|name| format!("--{name}"))
        .or_else(|| argument.get_short().map(|name| format!("-{name}")))?;
    let probe = command.clone();
    match probe.try_get_matches_from([command.get_name(), flag.as_str(), INVALID_VALUE]) {
        Err(error) if error.kind() == clap::error::ErrorKind::ValueValidation => {
            Some(error.to_string())
        }
        _ => None,
    }
}

fn json_artifact(contract: &Value) -> String {
    let mut artifact = serde_json::to_string_pretty(contract).expect("contract is serializable");
    artifact.push('\n');
    artifact
}

fn contract_matches(expected: &Value, actual: &Value) -> Result<(), String> {
    (expected == actual).then_some(()).ok_or_else(|| {
        "generated command contract no longer matches the Clap definition".to_owned()
    })
}

#[test]
fn command_contract_has_only_current_thin_commands() {
    let contract = command_contract();
    let commands = contract["subcommands"]
        .as_array()
        .expect("subcommands are an array")
        .iter()
        .map(|command| command["name"].as_str().expect("command has a name"))
        .collect::<Vec<_>>();
    assert_eq!(commands, ["log", "metric", "span"]);
}

#[test]
fn planted_command_definition_drift_is_detected() {
    let expected = command_contract();
    let drifted = Cli::command().subcommand(Command::new("planted-contract-drift"));
    let error = contract_matches(&expected, &command_contract_for(&drifted))
        .expect_err("a changed Clap command definition must invalidate the artifact");
    assert!(error.contains("no longer matches"));
}

#[test]
fn result_contract_matches_the_current_process_surface() {
    let contract = result_contract();
    let outcomes = contract["outcomes"]
        .as_array()
        .expect("outcomes are an array");
    assert!(outcomes.iter().any(|outcome| {
        outcome["case"] == "clap_usage_error"
            && outcome["exit_code"] == EXIT_USAGE
            && outcome["stderr"]["kind"] == "clap_rendered_multiline"
    }));
    assert!(outcomes.iter().any(|outcome| {
        outcome["case"] == "export_success"
            && outcome["exit_code"] == EXIT_OK
            && outcome["stdout"]["kind"] == "empty"
    }));
    assert!(outcomes.iter().any(|outcome| {
        outcome["case"] == "validation_error" && outcome["exit_code"] == EXIT_VALIDATION
    }));
    assert!(outcomes.iter().any(|outcome| {
        outcome["case"] == "export_error" && outcome["exit_code"] == EXIT_EXPORT
    }));
    assert!(outcomes.iter().any(|outcome| {
        outcome["case"] == "caught_panic" && outcome["exit_code"] == EXIT_INTERNAL
    }));
}

#[test]
fn documented_input_limits_and_timeout_match_the_registry() {
    use sc_observability_otlp::constants::{
        DEFAULT_OTLP_TIMEOUT_MS, MAX_BATCH_RECORDS, MAX_INPUT_BYTES,
    };

    const MEBIBYTE: usize = 1024 * 1024;
    assert_eq!(MAX_INPUT_BYTES % MEBIBYTE, 0);
    assert_eq!(DEFAULT_OTLP_TIMEOUT_MS % 1_000, 0);

    let input_mebibytes = MAX_INPUT_BYTES / MEBIBYTE;
    let timeout_seconds = DEFAULT_OTLP_TIMEOUT_MS / 1_000;
    let rendered_help = reference()
        .0
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace(',', "");

    for expected in [
        format!("At most {input_mebibytes} MiB and {MAX_BATCH_RECORDS} attributes"),
        format!("Input is limited to {input_mebibytes} MiB and {MAX_BATCH_RECORDS} attributes."),
        format!("Defaults to {timeout_seconds} seconds"),
    ] {
        assert!(
            rendered_help.contains(&expected.replace(',', "")),
            "generated CLI help does not match its registry value: {expected}"
        );
    }
    assert!(rendered_help.contains(
        "OTLP connection requests and exporter retries only; input reads may block until EOF"
    ));
    let manual = include_str!("manual.txt");
    assert!(manual.contains("wait until EOF"));
    assert!(manual.contains("bounds OTLP export only"));
}

#[test]
fn public_options_have_explanations() {
    fn check(command: &Command) {
        for arg in command.get_arguments().filter(|arg| !arg.is_hide_set()) {
            assert!(
                arg.get_help().is_some(),
                "{}: {} needs help",
                command.get_name(),
                arg.get_id()
            );
        }
        for child in command
            .get_subcommands()
            .filter(|child| !child.is_hide_set())
        {
            assert!(
                child.get_about().is_some(),
                "{} needs a description",
                child.get_name()
            );
            check(child);
        }
    }
    let mut command = Cli::command();
    command.build();
    check(&command);
}

#[test]
fn website_escapes_help_and_matches_markdown_commands() {
    assert_eq!(escape("<&\"'>"), "&lt;&amp;&quot;&#39;&gt;");
    let (markdown, html) = reference();
    for command in ["sc-otel", "sc-otel log", "sc-otel span", "sc-otel metric"] {
        assert!(markdown.contains(&format!("## {command}\n")));
        assert!(html.contains(&format!("<h2>{command}</h2>")));
    }
    assert!(!html.contains("<URL>"));
    assert!(html.contains("&lt;URL&gt;"));
}

#[test]
fn help_names_no_retired_store_command() {
    let (markdown, html) = reference();
    for retired in [
        "sc-otel emit",
        "sc-otel validate",
        "sc-otel flush",
        "sc-otel status",
        "--store",
        "--config",
        "--record-key",
        "--no-flush",
        "SQLite",
        "durable",
    ] {
        assert!(
            !markdown.contains(retired),
            "{retired} remains in the manual"
        );
        assert!(!html.contains(retired), "{retired} remains on the website");
    }
}

#[test]
fn manual_documents_removed_auth_header_and_handoff() {
    let manual = include_str!("manual.txt");
    assert!(manual.contains("does not read SC_OTEL_AUTH_HEADER"));
    assert!(manual.contains("ADR-023 supersedes"));

    let handoff = include_str!("../../../docs/plans/phase-h/h-2-to-h-4-cli-removal-handoff.md");
    assert!(handoff.contains("does not read `SC_OTEL_AUTH_HEADER`"));
    assert!(handoff.contains("ADR-023 supersedes ADR-021"));
    assert!(handoff.contains("do not map it to `Authorization`"));
}
